development:
  adapter: postgresql
  encoding: utf8
  database: blog_development
  username: postgres
  password: postgres
  host: localhost
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: blog_test
  username: postgres
  password: postgres
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: blog_production
  username: postgres
  password: postgres
  host: localhost
  pool: 5

